items:
  # See full list on https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  "first": "BLUE_DYE"
  "second": "RED_DYE"

messages:
  "prefix": "&#F0F8FF[TicTacToe] &r"
  "info": "&#318CE7Info:\n
  &#318CE7/ttc invite <Player>&#F0F8FF - invite a player to play tic tac toe\n
  &#318CE7/ttc accept&#F0F8FF - accept play request"
  "only-players": "&#CF1020Only players can use this command."
  "command-not-found": "&#CF1020Command wasn't found!"
  "provide-a-name": "&#CF1020Provide the name of a player to invite!"
  "player-wasnt-found": "&#CF1020Player wasn't found!"
  "cant-send-to-yourself": "&#CF1020You can't send a request to yourself!"
  "previous-request-was-deleted": "&#FECB00Your previous request was deleted!"
  "request-sent-successfully": "&#318CE7The request was sent &nsuccessfully!"
  "received-a-request": "&#318CE7You have received a request to play!\nType &n/ttc accept&r&#318CE7 to accept!"
  "request-to-play-wasnt-found": "&#CF1020The request wasn't found!"
  "request-was-accepted": "&#8EE53FYour play request was accepted!"
  "you-accepted-request": "&#8EE53FYou've accepted the request from %s."
  "you-won": "&#8EE53FYou won the game against &n%s&#8EE53F!"
  "you-lost": "&#CF1020You lost against &n%s&#CF1020!"
  "game-ended-draw": "&#FECB00Game ended draw!"
  "opponent-aborted-game": "&#318CE7Your opponent aborted the game! &#8EE53F&nYou are the winner!"
  "you-aborted-game": "&#CF1020You've aborted the game! You lost."

  # Gui messages (that are shown in game inventory)
  "gui-prefix": "[TTC] "
  "gui-player's-turn": "%s's turn!"
  "gui-draw": "Draw!"
  "gui-player-won": "%s won!"

  # Admin messages
  "plugin-reloaded": "&#318CE7Plugin was reloaded!"
  "failed-to-reload": "&#CF1020Plugin was failed to reload."