name: TicTacToe
version: '${project.version}'
main: net.justempire.tictactoe.TicTacToe
api-version: '1.20'

commands:
  tictactoe:
    description: Tic Tac Toe command
    aliases:
      - ttc

permissions:
  tictactoe.admin:
    description: Allows to reload the plugin
    default: op