name: TicTacToe
version: '${project.version}'
main: net.justempire.tictactoe.TicTacToe
api-version: '1.16'
author: 'mrquackduck'

commands:
  tictactoe:
    description: Tic Tac Toe command
    aliases:
      - ttt

permissions:
  tictactoe.admin:
    description: Allows a player to reload the plugin
    default: op
  tictactoe.invite:
    description: Allows a player to invite other players
    default: true
  tictactoe.accept:
    description: Allows a player to accept other player's invites
    default: true