name: TicTacToe
version: '${project.version}'
main: net.justempire.tictactoe.TicTacToe
api-version: '1.16'

commands:
  tictactoe:
    description: Tic Tac Toe command
    aliases:
      - ttt

permissions:
  tictactoe.admin:
    description: Allows to reload the plugin
    default: op